#%RAML 1.0
title: Asynchronous API
version: 1.0.0
mediaType: 
- application/json

types:
  job: 
    properties:
      status:
        enum: [IN PROGRESS, CANCELLED, FAILED, SUCCESS]
      start: string
      end: string
                
/resources:       
  get:
    description: Get list of tasks
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "tasks":[
                    {
                      "id":"21303",
                      "href":"/resources/21303"
                    },
                    {
                      "id":"21304",
                      "href":"/resources/21304"
                    }
                ]
              }
  post:
    description: Create a resource task
    responses:
      202:
        description: 
        headers:
          Location:
            example: /resources/21304
        body:
          example: |
            { 
              "id": "21304",
              "href": "/resources/21304"
            }            
  /{id}:
    get:
      description: Get a resource
      responses:
        200:
          body:
            type: job
            example: {status: "IN PROGRESS",start: "01-01-2013 10:50:45",end: ""}           
        303:
          body:
            type: job
            example: {status: "SUCCESS",start: "01-01-2013 10:50:45",end: "01-01-2014 10:50:45"}
        500:
          body:
            type: job
            example: {status: "FAILED",start: "01-01-2013 10:50:45",end: "01-01-2014 10:50:45"}
    delete:
      responses:
        200:
          description: Delete a resource
          body:
            type: job
            example: {status: "CANCELLED",start: "01-01-2013 10:50:45",end: "01-01-2014 10:50:45"}

/tasks/{id}:
  put:
    responses:
      200:
        body:
          application/json:
            example: {status: "UPDATED"}